// Stammdaten: Kategorien, Artikel-Katalog, Reisearten-Templates, Add-ons.
// Artikel: key -> [kategorie, name_de, name_en, defaultQty, prio, lastMinute]
// defaultQty: Zahl oder 'D' = tagesabhängig (Tage+1, max. 10)

const CATS = {
  dokumente:    { de: 'Dokumente & Geld', en: 'Documents & Money', icon: '🛂' },
  kleider:      { de: 'Kleider', en: 'Clothes', icon: '👕' },
  schuhe:       { de: 'Schuhe', en: 'Shoes', icon: '👟' },
  jacken:       { de: 'Jacken', en: 'Jackets', icon: '🧥' },
  hygiene:      { de: 'Hygieneartikel', en: 'Toiletries', icon: '🪥' },
  medikamente:  { de: 'Medikamente', en: 'Medication', icon: '💊' },
  elektronik:   { de: 'Elektronik', en: 'Electronics', icon: '🔌' },
  gadgets:      { de: 'Gadgets', en: 'Gadgets', icon: '🔦' },
  unterhaltung: { de: 'Unterhaltung', en: 'Entertainment', icon: '📚' },
  sport:        { de: 'Sport & Aktivität', en: 'Sports & Activity', icon: '🏃' },
  strand:       { de: 'Strand & Bad', en: 'Beach & Swim', icon: '🏖️' },
  winter:       { de: 'Winter & Schnee', en: 'Winter & Snow', icon: '❄️' },
  sonstiges:    { de: 'Sonstiges', en: 'Other', icon: '📦' },
};
const CAT_ORDER = ['dokumente','kleider','schuhe','jacken','hygiene','medikamente','elektronik','gadgets','unterhaltung','sport','strand','winter','sonstiges'];

const ITEMS = {
  // Dokumente & Geld
  reisepass:        ['dokumente','Reisepass','Passport',1,1,1],
  idkarte:          ['dokumente','ID-Karte','ID card',1,1,1],
  fuehrerschein:    ['dokumente','Führerschein','Driving licence',1,1,1],
  kreditkarte:      ['dokumente','Kreditkarte','Credit card',1,1,1],
  bargeld:          ['dokumente','Bargeld','Cash',1,1,1],
  tickets:          ['dokumente','Tickets / Bordkarten','Tickets / boarding passes',1,1,0],
  buchungen:        ['dokumente','Buchungsbestätigungen','Booking confirmations',1,2,0],
  versicherungskarte:['dokumente','Versicherungskarte','Insurance card',1,2,0],
  impfausweis:      ['dokumente','Impfausweis','Vaccination card',1,3,0],
  // Kleider
  unterhosen:       ['kleider','Unterhosen','Underwear','D',1,0],
  socken:           ['kleider','Socken','Socks','D',1,0],
  tshirts:          ['kleider','T-Shirts','T-shirts','D',1,0],
  hemden:           ['kleider','Hemden','Shirts',2,2,0],
  hosen_lang:       ['kleider','Lange Hosen','Long trousers',2,1,0],
  jeans:            ['kleider','Jeans','Jeans',1,2,0],
  shorts:           ['kleider','Shorts','Shorts',2,2,0],
  pullover:         ['kleider','Pullover','Sweater',1,2,0],
  pyjama:           ['kleider','Pyjama','Pyjamas',1,2,0],
  guertel:          ['kleider','Gürtel','Belt',1,2,0],
  badehose:         ['kleider','Badehose / Badeanzug','Swimwear',1,1,0],
  funktionsshirts:  ['kleider','Funktionsshirts','Technical shirts',2,2,0],
  wandersocken:     ['kleider','Wandersocken','Hiking socks',2,1,0],
  laufsocken:       ['kleider','Laufsocken','Running socks',2,2,0],
  running_hose:     ['kleider','Running-Hosen','Running shorts/tights',1,1,0],
  running_shirt:    ['kleider','Running-Shirts','Running shirts',2,1,0],
  radhose:          ['kleider','Radhose','Cycling shorts',1,1,0],
  radtrikot:        ['kleider','Radtrikot','Cycling jersey',1,2,0],
  thermounterwaesche:['kleider','Thermounterwäsche','Thermal underwear',1,2,0],
  skisocken:        ['kleider','Skisocken','Ski socks',2,1,0],
  business_hemden:  ['kleider','Business-Hemden','Business shirts',2,1,0],
  anzug:            ['kleider','Anzug','Suit',1,1,0],
  krawatte:         ['kleider','Krawatte','Tie',1,3,0],
  blazer:           ['kleider','Blazer / Sakko','Blazer',1,2,0],
  // Schuhe
  sneakers:         ['schuhe','Sneakers','Sneakers',1,1,0],
  wanderschuhe:     ['schuhe','Wanderschuhe','Hiking boots',1,1,0],
  laufschuhe:       ['schuhe','Laufschuhe','Running shoes',1,1,0],
  sandalen:         ['schuhe','Sandalen','Sandals',1,3,0],
  flipflops:        ['schuhe','Flipflops','Flip-flops',1,2,0],
  business_schuhe:  ['schuhe','Business-Schuhe','Business shoes',1,1,0],
  skischuhe:        ['schuhe','Skischuhe','Ski boots',1,1,0],
  radschuhe:        ['schuhe','Radschuhe','Cycling shoes',1,2,0],
  huettenschuhe:    ['schuhe','Hüttenschuhe','Hut slippers',1,3,0],
  // Jacken
  regenjacke:       ['jacken','Regenjacke','Rain jacket',1,1,0],
  daunenjacke:      ['jacken','Daunenjacke','Down jacket',1,2,0],
  fleecejacke:      ['jacken','Fleecejacke','Fleece jacket',1,2,0],
  softshell:        ['jacken','Softshell-Jacke','Softshell jacket',1,2,0],
  skijacke:         ['jacken','Skijacke','Ski jacket',1,1,0],
  skihose:          ['jacken','Skihose','Ski trousers',1,1,0],
  windweste:        ['jacken','Windweste','Wind vest',1,3,0],
  mantel:           ['jacken','Mantel','Coat',1,3,0],
  // Hygiene
  zahnbuerste:      ['hygiene','Zahnbürste','Toothbrush',1,1,1],
  zahnpasta:        ['hygiene','Zahnpasta','Toothpaste',1,1,1],
  deo:              ['hygiene','Deo','Deodorant',1,1,1],
  duschgel:         ['hygiene','Duschgel','Shower gel',1,2,0],
  shampoo:          ['hygiene','Shampoo','Shampoo',1,2,0],
  rasierer:         ['hygiene','Rasierer','Razor',1,2,1],
  sonnencreme:      ['hygiene','Sonnencreme','Sunscreen',1,1,0],
  after_sun:        ['hygiene','After Sun','After sun',1,3,0],
  kontaktlinsen:    ['hygiene','Kontaktlinsen / Brille','Contact lenses / glasses',1,1,1],
  linsenmittel:     ['hygiene','Linsenmittel','Lens solution',1,2,0],
  nagelset:         ['hygiene','Nagelset','Nail kit',1,3,0],
  ohrstoepsel:      ['hygiene','Ohrstöpsel','Earplugs',1,3,0],
  taschentuecher:   ['hygiene','Taschentücher','Tissues',2,3,0],
  labello:          ['hygiene','Lippenbalsam','Lip balm',1,3,0],
  haarbuerste:      ['hygiene','Haarbürste / Kamm','Hairbrush / comb',1,2,1],
  // Medikamente
  medis:            ['medikamente','Persönliche Medikamente','Personal medication',1,1,1],
  schmerzmittel:    ['medikamente','Schmerzmittel','Painkillers',1,2,0],
  pflaster:         ['medikamente','Pflaster','Plasters',1,2,0],
  blasenpflaster:   ['medikamente','Blasenpflaster','Blister plasters',1,2,0],
  desinfektion:     ['medikamente','Desinfektionsmittel','Disinfectant',1,3,0],
  insektenschutz:   ['medikamente','Insektenschutz','Insect repellent',1,2,0],
  reisetabletten:   ['medikamente','Reisetabletten','Motion sickness pills',1,3,0],
  durchfallmittel:  ['medikamente','Durchfallmittel','Anti-diarrhoea meds',1,2,0],
  elektrolyte:      ['medikamente','Elektrolyte','Electrolytes',1,3,0],
  // Elektronik
  handy_ladekabel:  ['elektronik','Handy-Ladekabel','Phone charger',1,1,1],
  powerbank:        ['elektronik','Powerbank','Power bank',1,2,1],
  adapter:          ['elektronik','Reiseadapter','Travel adapter',1,1,0],
  kopfhoerer:       ['elektronik','Kopfhörer','Headphones',1,2,1],
  laptop:           ['elektronik','Laptop + Ladegerät','Laptop + charger',1,1,1],
  tablet:           ['elektronik','Tablet','Tablet',1,3,1],
  kamera:           ['elektronik','Kamera','Camera',1,3,0],
  kamera_zubehoer:  ['elektronik','Kamera-Ladegerät + Speicherkarten','Camera charger + memory cards',1,3,0],
  ebook_reader:     ['elektronik','E-Book-Reader','E-book reader',1,3,1],
  smartwatch_kabel: ['elektronik','Smartwatch-Ladekabel','Smartwatch charger',1,2,0],
  steckerleiste:    ['elektronik','Steckerleiste','Power strip',1,3,0],
  auto_ladekabel:   ['elektronik','Auto-Ladekabel / Halterung','Car charger / mount',1,2,0],
  // Gadgets
  taschenmesser:    ['gadgets','Taschenmesser','Pocket knife',1,3,0],
  stirnlampe:       ['gadgets','Stirnlampe','Headlamp',1,2,0],
  fernglas:         ['gadgets','Fernglas','Binoculars',1,3,0],
  packwuerfel:      ['gadgets','Packwürfel','Packing cubes',1,3,0],
  waeschebeutel:    ['gadgets','Wäschebeutel','Laundry bag',1,3,0],
  reisekissen:      ['gadgets','Reisekissen','Travel pillow',1,3,0],
  schlafmaske:      ['gadgets','Schlafmaske','Sleep mask',1,3,0],
  trinkflasche:     ['gadgets','Trinkflasche','Water bottle',1,2,0],
  thermosflasche:   ['gadgets','Thermosflasche','Thermos flask',1,3,0],
  vorhaengeschloss: ['gadgets','Vorhängeschloss','Padlock',1,3,0],
  regenschirm:      ['gadgets','Regenschirm','Umbrella',1,3,0],
  sonnenbrille:     ['gadgets','Sonnenbrille','Sunglasses',1,1,0],
  // Unterhaltung
  buch:             ['unterhaltung','Buch','Book',1,3,0],
  zeitschriften:    ['unterhaltung','Zeitschriften','Magazines',1,3,0],
  spiele:           ['unterhaltung','Reisespiele','Travel games',1,3,0],
  kartenspiel:      ['unterhaltung','Kartenspiel','Card game',1,3,0],
  reisefuehrer:     ['unterhaltung','Reiseführer','Travel guide',1,3,0],
  tagebuch:         ['unterhaltung','Notizbuch + Stift','Notebook + pen',1,3,0],
  // Sport & Aktivität
  laufuhr:          ['sport','Laufuhr / GPS-Uhr','Running / GPS watch',1,1,1],
  laufgurt:         ['sport','Laufgurt / Race-Weste','Running belt / race vest',1,2,0],
  gels:             ['sport','Gels / Sportverpflegung','Gels / sports nutrition',4,2,0],
  startnummernband: ['sport','Startnummernband','Race number belt',1,2,0],
  wanderstoecke:    ['sport','Wanderstöcke','Trekking poles',1,2,0],
  rucksack_regenhuelle:['sport','Regenhülle Rucksack','Backpack rain cover',1,2,0],
  wanderkarte:      ['sport','Wanderkarte / GPS','Hiking map / GPS',1,2,0],
  erste_hilfe:      ['sport','Erste-Hilfe-Set','First aid kit',1,1,0],
  schlafsack_huette:['sport','Hüttenschlafsack','Hut sleeping liner',1,1,0],
  tauchcomputer:    ['sport','Tauchcomputer','Dive computer',1,1,0],
  maske_schnorchel: ['sport','Maske + Schnorchel','Mask + snorkel',1,1,0],
  flossen:          ['sport','Flossen','Fins',1,2,0],
  neoprenanzug:     ['sport','Neoprenanzug','Wetsuit',1,2,0],
  tauchschein:      ['sport','Brevet + Logbuch','Certification + logbook',1,1,0],
  schwimmbrille:    ['sport','Schwimmbrille','Swim goggles',1,2,0],
  velohelm:         ['sport','Velohelm','Bike helmet',1,1,0],
  radhandschuhe:    ['sport','Radhandschuhe','Cycling gloves',1,2,0],
  radbrille:        ['sport','Radbrille','Cycling glasses',1,2,0],
  flickzeug:        ['sport','Flickzeug + Pumpe','Repair kit + pump',1,1,0],
  veloschloss:      ['sport','Veloschloss','Bike lock',1,2,0],
  velolicht:        ['sport','Velolicht','Bike lights',1,2,0],
  // Strand & Bad
  badetuch:         ['strand','Badetuch','Beach towel',1,1,0],
  strandtasche:     ['strand','Strandtasche','Beach bag',1,3,0],
  sonnenhut:        ['strand','Sonnenhut / Cap','Sun hat / cap',1,2,0],
  luftmatratze:     ['strand','Luftmatratze','Air mattress',1,3,0],
  kuehltasche:      ['strand','Kühltasche','Cooler bag',1,3,0],
  // Winter & Schnee
  muetze:           ['winter','Mütze','Beanie',1,1,0],
  handschuhe:       ['winter','Handschuhe','Gloves',1,1,0],
  schal:            ['winter','Schal / Buff','Scarf / buff',1,2,0],
  skihandschuhe:    ['winter','Skihandschuhe','Ski gloves',1,1,0],
  skibrille:        ['winter','Skibrille','Ski goggles',1,1,0],
  skihelm:          ['winter','Skihelm','Ski helmet',1,1,0],
  handwaermer:      ['winter','Handwärmer','Hand warmers',2,3,0],
  felle:            ['winter','Felle','Climbing skins',1,1,0],
  lvs:              ['winter','LVS-Gerät','Avalanche transceiver',1,1,0],
  schaufel_sonde:   ['winter','Schaufel + Sonde','Shovel + probe',1,1,0],
  tourenstoecke:    ['winter','Tourenstöcke','Touring poles',1,1,0],
  harscheisen:      ['winter','Harscheisen','Ski crampons',1,2,0],
  // Sonstiges
  schluessel:       ['sonstiges','Hausschlüssel','House keys',1,1,1],
  snacks:           ['sonstiges','Snacks für die Reise','Travel snacks',1,3,1],
  waschmittel:      ['sonstiges','Reisewaschmittel','Travel detergent',1,3,0],
  zip_beutel:       ['sonstiges','Zip-Beutel','Zip bags',3,3,0],
  muellsack:        ['sonstiges','Müll-/Wäschesack','Trash / laundry bag',1,3,0],
  daypack_item:     ['sonstiges','Faltbarer Daypack','Foldable daypack',1,3,0],
};

// Reisearten mit Template (Basis-Artikel; 'D'-Mengen werden aus der Reisedauer berechnet)
const TRIP_TYPES = {
  staedtetrip:  { de: 'Städtetrip', en: 'City trip', icon: '🏙️',
    items: ['idkarte','kreditkarte','bargeld','tickets','buchungen','unterhosen','socken','tshirts','hemden','jeans','hosen_lang','pullover','pyjama','guertel','sneakers','regenjacke','zahnbuerste','zahnpasta','deo','duschgel','rasierer','haarbuerste','medis','handy_ladekabel','powerbank','kopfhoerer','sonnenbrille','buch','reisefuehrer','schluessel','regenschirm'] },
  strandferien: { de: 'Strandferien', en: 'Beach holiday', icon: '🏖️',
    items: ['reisepass','kreditkarte','bargeld','tickets','buchungen','versicherungskarte','unterhosen','socken','tshirts','shorts','hemden','hosen_lang','pyjama','badehose','sandalen','flipflops','sneakers','zahnbuerste','zahnpasta','deo','duschgel','shampoo','rasierer','haarbuerste','sonnencreme','after_sun','labello','medis','insektenschutz','handy_ladekabel','powerbank','kopfhoerer','adapter','sonnenbrille','sonnenhut','badetuch','strandtasche','buch','ebook_reader','kartenspiel','schluessel'] },
  wanderferien: { de: 'Wanderferien', en: 'Hiking holiday', icon: '🥾',
    items: ['idkarte','kreditkarte','bargeld','buchungen','unterhosen','wandersocken','socken','tshirts','funktionsshirts','hosen_lang','shorts','pullover','pyjama','wanderschuhe','sneakers','regenjacke','fleecejacke','softshell','zahnbuerste','zahnpasta','deo','duschgel','sonnencreme','labello','medis','schmerzmittel','pflaster','blasenpflaster','handy_ladekabel','powerbank','sonnenbrille','trinkflasche','wanderstoecke','rucksack_regenhuelle','wanderkarte','erste_hilfe','muetze','taschenmesser','schluessel'] },
  trekkingtour: { de: 'Trekkingtour', en: 'Trekking tour', icon: '🏔️',
    items: ['reisepass','kreditkarte','bargeld','buchungen','versicherungskarte','unterhosen','wandersocken','funktionsshirts','hosen_lang','shorts','pullover','thermounterwaesche','wanderschuhe','huettenschuhe','regenjacke','fleecejacke','daunenjacke','zahnbuerste','zahnpasta','deo','sonnencreme','labello','medis','schmerzmittel','pflaster','blasenpflaster','desinfektion','elektrolyte','handy_ladekabel','powerbank','stirnlampe','sonnenbrille','trinkflasche','wanderstoecke','rucksack_regenhuelle','wanderkarte','erste_hilfe','schlafsack_huette','muetze','handschuhe','taschenmesser','waschmittel','zip_beutel','schluessel'] },
  weekendtrip:  { de: 'Weekendtrip', en: 'Weekend trip', icon: '🎒',
    items: ['idkarte','kreditkarte','bargeld','tickets','unterhosen','socken','tshirts','hemden','jeans','pullover','pyjama','sneakers','zahnbuerste','zahnpasta','deo','rasierer','haarbuerste','medis','handy_ladekabel','kopfhoerer','sonnenbrille','buch','schluessel'] },
  businesstrip: { de: 'Businesstrip', en: 'Business trip', icon: '💼',
    items: ['idkarte','reisepass','kreditkarte','tickets','buchungen','unterhosen','socken','business_hemden','anzug','blazer','krawatte','guertel','pyjama','tshirts','business_schuhe','sneakers','zahnbuerste','zahnpasta','deo','rasierer','haarbuerste','medis','laptop','handy_ladekabel','powerbank','kopfhoerer','adapter','tagebuch','schluessel'] },
  skiferien:    { de: 'Skiferien', en: 'Ski holiday', icon: '⛷️',
    items: ['idkarte','kreditkarte','bargeld','buchungen','versicherungskarte','unterhosen','skisocken','socken','tshirts','funktionsshirts','thermounterwaesche','hosen_lang','pullover','pyjama','skischuhe','sneakers','huettenschuhe','skijacke','skihose','fleecejacke','zahnbuerste','zahnpasta','deo','duschgel','sonnencreme','labello','medis','schmerzmittel','handy_ladekabel','powerbank','sonnenbrille','skibrille','skihelm','skihandschuhe','muetze','schal','handwaermer','badehose','schluessel'] },
  skitour:      { de: 'Skitour', en: 'Ski touring', icon: '🎿',
    items: ['idkarte','kreditkarte','bargeld','unterhosen','skisocken','funktionsshirts','thermounterwaesche','pullover','skischuhe','skijacke','skihose','fleecejacke','daunenjacke','zahnbuerste','zahnpasta','deo','sonnencreme','labello','medis','schmerzmittel','handy_ladekabel','powerbank','stirnlampe','sonnenbrille','skibrille','skihelm','skihandschuhe','handschuhe','muetze','schal','felle','lvs','schaufel_sonde','tourenstoecke','harscheisen','erste_hilfe','trinkflasche','thermosflasche','snacks','schluessel'] },
  runningrace:  { de: 'Running Race', en: 'Running race', icon: '🏅',
    items: ['idkarte','kreditkarte','tickets','buchungen','unterhosen','socken','laufsocken','tshirts','running_hose','running_shirt','pullover','pyjama','laufschuhe','sneakers','regenjacke','zahnbuerste','zahnpasta','deo','duschgel','medis','schmerzmittel','blasenpflaster','elektrolyte','handy_ladekabel','laufuhr','laufgurt','gels','startnummernband','sonnenbrille','trinkflasche','schluessel'] },
  tauchferien:  { de: 'Tauchferien', en: 'Diving holiday', icon: '🤿',
    items: ['reisepass','kreditkarte','bargeld','tickets','buchungen','versicherungskarte','unterhosen','socken','tshirts','shorts','badehose','pyjama','sandalen','flipflops','sneakers','zahnbuerste','zahnpasta','deo','duschgel','sonnencreme','after_sun','medis','reisetabletten','durchfallmittel','insektenschutz','handy_ladekabel','powerbank','adapter','sonnenbrille','sonnenhut','badetuch','tauchcomputer','maske_schnorchel','flossen','neoprenanzug','tauchschein','buch','schluessel'] },
  leer:         { de: 'Leere Liste', en: 'Empty list', icon: '📝', items: [] },
  bikeferien:   { de: 'Bikeferien', en: 'Bike holiday', icon: '🚵',
    items: ['idkarte','kreditkarte','bargeld','buchungen','unterhosen','socken','tshirts','radhose','radtrikot','shorts','pullover','pyjama','radschuhe','sneakers','regenjacke','windweste','zahnbuerste','zahnpasta','deo','duschgel','sonnencreme','medis','schmerzmittel','pflaster','handy_ladekabel','powerbank','velohelm','radhandschuhe','radbrille','flickzeug','veloschloss','velolicht','trinkflasche','erste_hilfe','schluessel'] },
};

// Aktivitäts-Module (ergänzen das Reiseart-Template)
const ACTIVITIES = {
  wandern:   { de: 'Wandern', en: 'Hiking', icon: '🥾',
    items: ['wanderschuhe','wandersocken','funktionsshirts','regenjacke','wanderstoecke','trinkflasche','erste_hilfe','rucksack_regenhuelle','blasenpflaster','sonnencreme','muetze'] },
  trekking:  { de: 'Trekking', en: 'Trekking', icon: '🏔️',
    items: ['wanderschuhe','wandersocken','funktionsshirts','regenjacke','daunenjacke','wanderstoecke','trinkflasche','erste_hilfe','stirnlampe','schlafsack_huette','waschmittel'] },
  running:   { de: 'Running', en: 'Running', icon: '🏃',
    items: ['laufschuhe','laufsocken','running_hose','running_shirt','laufuhr','laufgurt'] },
  biken:     { de: 'Biken', en: 'Cycling', icon: '🚴',
    items: ['velohelm','radhose','radtrikot','radhandschuhe','radbrille','radschuhe','flickzeug','velolicht','veloschloss','trinkflasche'] },
  tauchen:   { de: 'Tauchen', en: 'Diving', icon: '🤿',
    items: ['tauchcomputer','maske_schnorchel','flossen','neoprenanzug','tauchschein','badehose','badetuch'] },
  schwimmen: { de: 'Schwimmen', en: 'Swimming', icon: '🏊',
    items: ['badehose','schwimmbrille','badetuch'] },
  business:  { de: 'Business', en: 'Business', icon: '💼',
    items: ['business_hemden','anzug','blazer','business_schuhe','laptop','tagebuch'] },
  skifahren: { de: 'Skifahren', en: 'Skiing', icon: '⛷️',
    items: ['skischuhe','skijacke','skihose','skisocken','skihelm','skibrille','skihandschuhe','thermounterwaesche'] },
};

// Transportmittel (mit optionalen Zusatz-Artikeln)
const TRANSPORT = {
  flugzeug:    { de: 'Flugzeug', en: 'Plane', icon: '✈️', items: ['reisepass','tickets','reisekissen','ohrstoepsel','kopfhoerer'] },
  zug:         { de: 'Zug', en: 'Train', icon: '🚆', items: ['tickets','kopfhoerer','snacks'] },
  eigenes_auto:{ de: 'Eigenes Auto', en: 'Own car', icon: '🚗', items: ['fuehrerschein','auto_ladekabel','snacks'] },
  mietauto:    { de: 'Mietauto', en: 'Rental car', icon: '🚙', items: ['fuehrerschein','kreditkarte','auto_ladekabel'] },
  bus:         { de: 'Bus', en: 'Bus', icon: '🚌', items: ['tickets','reisekissen','snacks'] },
  taxi:        { de: 'Taxi', en: 'Taxi', icon: '🚕', items: [] },
  fahrrad:     { de: 'Fahrrad', en: 'Bicycle', icon: '🚲', items: ['velohelm','veloschloss','flickzeug'] },
  zu_fuss:     { de: 'Zu Fuss', en: 'On foot', icon: '🚶', items: [] },
};

// Gepäckstücke
const LUGGAGE = {
  koffer_gross:     { de: 'Rollkoffer gross', en: 'Large suitcase', icon: '🧳' },
  koffer_mittel:    { de: 'Rollkoffer mittel', en: 'Medium suitcase', icon: '🧳' },
  koffer_klein:     { de: 'Rollkoffer klein', en: 'Small suitcase', icon: '🧳' },
  handgepaeck:      { de: 'Handgepäck-Trolley', en: 'Carry-on trolley', icon: '🛄' },
  trekking_rucksack:{ de: 'Trekking-Rucksack', en: 'Trekking backpack', icon: '🎒' },
  daypack:          { de: 'Daypack', en: 'Daypack', icon: '🎒' },
  sporttasche:      { de: 'Sporttasche', en: 'Duffel bag', icon: '👜' },
  skisack:          { de: 'Skisack', en: 'Ski bag', icon: '🎿' },
  velokoffer:       { de: 'Velokoffer / Bike Bag', en: 'Bike bag', icon: '🚲' },
};

// Klima / Reisezeit (ergänzen Artikel)
const CLIMATE = {
  heiss:     { de: 'Heiss', en: 'Hot', icon: '🥵', items: ['sonnencreme','sonnenhut','sonnenbrille','shorts','trinkflasche'] },
  warm:      { de: 'Warm', en: 'Warm', icon: '☀️', items: ['sonnencreme','sonnenbrille','shorts'] },
  mild:      { de: 'Mild', en: 'Mild', icon: '⛅', items: ['pullover','regenjacke'] },
  kalt:      { de: 'Kalt', en: 'Cold', icon: '🥶', items: ['muetze','handschuhe','schal','thermounterwaesche','daunenjacke'] },
  regnerisch:{ de: 'Regnerisch', en: 'Rainy', icon: '🌧️', items: ['regenjacke','regenschirm'] },
  schnee:    { de: 'Schnee', en: 'Snow', icon: '❄️', items: ['muetze','handschuhe','schal','thermounterwaesche'] },
};

// Final Check: kritische Artikel, die je nach Kontext nicht fehlen dürfen
const CRITICAL = {
  always: ['medis', 'zahnbuerste', 'handy_ladekabel', 'kreditkarte'],
  tripTypes: {
    strandferien: ['sonnencreme', 'badehose', 'sonnenbrille', 'badetuch'],
    wanderferien: ['wanderschuhe', 'regenjacke', 'sonnencreme', 'trinkflasche', 'blasenpflaster'],
    trekkingtour: ['wanderschuhe', 'regenjacke', 'erste_hilfe', 'stirnlampe', 'blasenpflaster'],
    businesstrip: ['laptop', 'business_hemden', 'business_schuhe'],
    skiferien: ['skihandschuhe', 'skibrille', 'skihelm', 'skisocken', 'sonnencreme'],
    skitour: ['lvs', 'schaufel_sonde', 'felle', 'skihelm', 'sonnencreme'],
    runningrace: ['laufschuhe', 'laufsocken', 'startnummernband', 'gels'],
    tauchferien: ['tauchschein', 'badehose', 'sonnencreme'],
    bikeferien: ['velohelm', 'flickzeug', 'radhose'],
  },
  climate: {
    heiss: ['sonnencreme', 'sonnenbrille', 'sonnenhut'],
    warm: ['sonnencreme'],
    kalt: ['muetze', 'handschuhe'],
    schnee: ['muetze', 'handschuhe'],
    regnerisch: ['regenjacke'],
  },
  transport: {
    flugzeug: ['reisepass', 'tickets'],
    mietauto: ['fuehrerschein', 'kreditkarte'],
    eigenes_auto: ['fuehrerschein'],
    fahrrad: ['velohelm'],
  },
  activities: {
    wandern: ['wanderschuhe', 'regenjacke'],
    trekking: ['wanderschuhe', 'erste_hilfe'],
    running: ['laufschuhe'],
    biken: ['velohelm'],
    tauchen: ['tauchschein'],
    schwimmen: ['badehose'],
    business: ['laptop'],
    skifahren: ['skihelm', 'skihandschuhe'],
  },
};

// Rückreise-Checkliste: Basis-Checks + kontextabhängige (cond = Transport-Key)
const RETURN_CHECKS = {
  safe:        { de: 'Hotel-Safe geleert', en: 'Hotel safe emptied', cond: null },
  kuehlschrank:{ de: 'Kühlschrank / Minibar geleert', en: 'Fridge / minibar emptied', cond: null },
  ladegeraete: { de: 'Ladegeräte & Kabel eingesammelt (alle Steckdosen absuchen)', en: 'Chargers & cables collected (check all outlets)', cond: null },
  bad:         { de: 'Badezimmer geräumt (Zahnbürste, Duschgel, Rasierer)', en: 'Bathroom cleared (toothbrush, shower gel, razor)', cond: null },
  schraenke:   { de: 'Schränke & Schubladen kontrolliert', en: 'Wardrobes & drawers checked', cond: null },
  bett:        { de: 'Unter dem Bett & hinter Vorhängen nachgeschaut', en: 'Checked under the bed & behind curtains', cond: null },
  balkon:      { de: 'Balkon / Terrasse kontrolliert', en: 'Balcony / terrace checked', cond: null },
  waesche:     { de: 'Hängende Wäsche / Kleider im Bad eingepackt', en: 'Hanging laundry / clothes in bathroom packed', cond: null },
  dokumente:   { de: 'Reisedokumente & Wertsachen eingepackt', en: 'Travel documents & valuables packed', cond: null },
  souvenirs:   { de: 'Souvenirs & Einkäufe verstaut', en: 'Souvenirs & purchases stowed', cond: null },
  schluessel:  { de: 'Zimmerschlüssel / Karte abgegeben', en: 'Room key / card returned', cond: null },
  checkin:     { de: 'Online-Check-in für Rückflug gemacht', en: 'Online check-in for return flight done', cond: 'flugzeug' },
  fluessig:    { de: 'Flüssigkeiten & Powerbank korrekt ins Gepäck verteilt', en: 'Liquids & power bank packed correctly', cond: 'flugzeug' },
  mietauto_kabel: { de: 'Alle Kabel & Gegenstände aus dem Mietauto entfernt (auch Handschuhfach)', en: 'All cables & items removed from rental car (incl. glovebox)', cond: 'mietauto' },
  mietauto_tanken:{ de: 'Mietauto vollgetankt', en: 'Rental car refuelled', cond: 'mietauto' },
  mietauto_fotos: { de: 'Mietauto bei Rückgabe fotografiert (Schäden dokumentieren)', en: 'Photographed rental car at return (document condition)', cond: 'mietauto' },
  auto_kabel:  { de: 'Ladekabel & Halterung aus dem Auto mitgenommen', en: 'Charger & mount taken from the car', cond: 'eigenes_auto' },
  tickets_rueck: { de: 'Tickets für die Rückreise bereit', en: 'Return tickets ready', cond: 'zug' },
};

// Länder (Auswahl für Settings, Basis für spätere Adapter-Hinweise)
const COUNTRIES = ['CH','DE','AT','FR','IT','ES','PT','GB','US','other'];
const COUNTRY_NAMES = {
  CH: { de: 'Schweiz', en: 'Switzerland' },
  DE: { de: 'Deutschland', en: 'Germany' },
  AT: { de: 'Österreich', en: 'Austria' },
  FR: { de: 'Frankreich', en: 'France' },
  IT: { de: 'Italien', en: 'Italy' },
  ES: { de: 'Spanien', en: 'Spain' },
  PT: { de: 'Portugal', en: 'Portugal' },
  GB: { de: 'Grossbritannien', en: 'United Kingdom' },
  US: { de: 'USA', en: 'United States' },
  other: { de: 'Anderes Land', en: 'Other country' },
};

// Spezifische Emojis pro Artikel (Fallback: Kategorie-Icon)
const ITEM_EMOJI = {
  reisepass: '🛂', idkarte: '🪪', fuehrerschein: '🪪', kreditkarte: '💳', bargeld: '💵',
  tickets: '🎫', buchungen: '📄', versicherungskarte: '🏥', impfausweis: '💉',
  unterhosen: '🩲', socken: '🧦', tshirts: '👕', hemden: '👔', hosen_lang: '👖', jeans: '👖',
  shorts: '🩳', pullover: '🧶', pyjama: '🛌', guertel: '➰', badehose: '🩱',
  funktionsshirts: '🎽', wandersocken: '🧦', laufsocken: '🧦', running_hose: '🩳',
  running_shirt: '🎽', radhose: '🚴', radtrikot: '🚴', thermounterwaesche: '🧊',
  skisocken: '🧦', business_hemden: '👔', anzug: '🤵', krawatte: '👔', blazer: '🧥',
  sneakers: '👟', wanderschuhe: '🥾', laufschuhe: '👟', sandalen: '🩴', flipflops: '🩴',
  business_schuhe: '👞', skischuhe: '🎿', radschuhe: '👟', huettenschuhe: '🥿',
  regenjacke: '🌧️', daunenjacke: '🧥', fleecejacke: '🧥', softshell: '🧥',
  skijacke: '🎿', skihose: '🎿', windweste: '🦺', mantel: '🧥',
  zahnbuerste: '🪥', zahnpasta: '🦷', deo: '🧴', duschgel: '🧴', shampoo: '🧴',
  rasierer: '🪒', sonnencreme: '🧴', after_sun: '🧴', kontaktlinsen: '👓',
  linsenmittel: '💧', nagelset: '💅', ohrstoepsel: '👂', taschentuecher: '🤧',
  labello: '💄', haarbuerste: '🪮',
  medis: '💊', schmerzmittel: '💊', pflaster: '🩹', blasenpflaster: '🩹',
  desinfektion: '🧼', insektenschutz: '🦟', reisetabletten: '🤢', durchfallmittel: '💊', elektrolyte: '🧂',
  handy_ladekabel: '🔌', powerbank: '🔋', adapter: '🔌', kopfhoerer: '🎧', laptop: '💻',
  tablet: '📱', kamera: '📷', kamera_zubehoer: '💾', ebook_reader: '📖',
  smartwatch_kabel: '⌚', steckerleiste: '🔌', auto_ladekabel: '🚗',
  taschenmesser: '🔪', stirnlampe: '🔦', fernglas: '🔭', packwuerfel: '🧊',
  waeschebeutel: '🧺', reisekissen: '💤', schlafmaske: '😴', trinkflasche: '🚰',
  thermosflasche: '☕', vorhaengeschloss: '🔒', regenschirm: '☂️', sonnenbrille: '🕶️',
  buch: '📕', zeitschriften: '📰', spiele: '🎲', kartenspiel: '🃏', reisefuehrer: '🗺️', tagebuch: '📓',
  laufuhr: '⌚', laufgurt: '🎽', gels: '🍬', startnummernband: '🏷️', wanderstoecke: '🥢',
  rucksack_regenhuelle: '🎒', wanderkarte: '🗺️', erste_hilfe: '⛑️', schlafsack_huette: '🛏️',
  tauchcomputer: '⌚', maske_schnorchel: '🤿', flossen: '🐬', neoprenanzug: '🥽',
  tauchschein: '📇', schwimmbrille: '🥽', velohelm: '⛑️', radhandschuhe: '🧤',
  radbrille: '🕶️', flickzeug: '🔧', veloschloss: '🔒', velolicht: '💡',
  badetuch: '🏖️', strandtasche: '👜', sonnenhut: '👒', luftmatratze: '🛟', kuehltasche: '🧊',
  muetze: '🧢', handschuhe: '🧤', schal: '🧣', skihandschuhe: '🧤', skibrille: '🥽',
  skihelm: '⛑️', handwaermer: '🔥', felle: '🦭', lvs: '📡', schaufel_sonde: '🪏',
  tourenstoecke: '🥢', harscheisen: '⚙️',
  schluessel: '🔑', snacks: '🍫', waschmittel: '🧼', zip_beutel: '🛍️', muellsack: '🗑️', daypack_item: '🎒',
};
